/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Programming',
      collapsed: true,
      items: [
        'programming/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Computer architecture',
      collapsed: true,
      items: [
        'computer-architecture/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Data structures and algorithms',
      collapsed: true,
      items: [
        'dsa/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Math for CS',
      collapsed: true,
      items: [
        'math-for-cs/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Operating systems',
      collapsed: true,
      items: [
        'operating-systems/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Computer networking',
      collapsed: true,
      items: [
        'computer-networking/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Databases',
      collapsed: true,
      items: [
        'databases/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Languages and compilers',
      collapsed: true,
      items: [
        'languages-and-compilers/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Distributed systems',
      collapsed: true,
      items: [
        'distributed-systems/introduction',
      ]
    },
    {
      type: 'category',
      label: 'Supplemental resources',
      collapsed: true,
      items: [
        'supplemental-resources/introduction',
      ]
    },
    {
      type: 'category',
      label: 'SSBA (standalone course)',
      collapsed: true,
      items: [
        'ssba/introduction',
        'ssba/class-1',
        'ssba/class-2',
        'ssba/class-3',
        'ssba/class-4',
        'ssba/class-5',
        'ssba/class-6',
        'ssba/class-7',
        'ssba/class-8',
        'ssba/class-9',
        'ssba/class-10',
        'ssba/class-11',
        'ssba/class-12',
        'ssba/class-13',
        'ssba/class-14',
        'ssba/class-15',
        'ssba/class-16',
      ]
    },
    'reference-list',
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
